apiVersion: v1
kind: Service
metadata:
  name: vega-service
spec:
  type: NodePort
  selector:
    app: vega
  ports:
    - name: "http-service"
      protocol: TCP
      port: 2789
      targetPort: 2789
      nodePort: 32101
    - name: "http-console"
      protocol: TCP
      port: 2847
      targetPort: 2847
      nodePort: 32102